# arxivの学問領域の指定
subject: 'cat:cs.*'　

# 検索キーワード
keywords:
        chemistry: 10
        antioxidant: 10
        molecule: 10
        compound: 10
        QSAR: 10
        Psi4: 10
        MOPAC: 10
        chemoinfomatics: 10
        cheminfomatics: 10
        NLP: 5
        AI: 5
           
# 通知の閾値
score_threshold: 10
