# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        chemistry: 10
        antioxidant: 10
        molecule: 10
        compound: 10
        QSAR: 10
        MI: 5
        NLP: 5
        AI: 5
           
# 通知の閾値
score_threshold: 10
